### ISSUE TITLE
Add a new readme style text file to the repository to outline project development

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/drupal8-composer-docksal#9]
At the Kanopi retreat, I presented the idea of having an additional readme style document in each of our repositories to help add additional documentation to the project to help onboard new developers, pass off to support at the end of the build, and write case studies after the project launches.

This doc would define the development of the project, not just the code as a traditional readme file does.

## Some ideas on the file name:
kanopi.md
development.md
project-description.md

### About the Project
Use this space to describe the project, timeline, and client.

### Team
Add Kanopi and Client names and roles.

### Important Links
[Teamwork](link_url)
[Github](link_url)
[Google Drive](link_url)
[Sketch Cloud](link_url)
[UXPin](link_url)
[etc](link_url)

### Development Notes
Add notes as you go.  Which modules did you choose and why?  Did you try anything that failed?  Tell me ongoing stories about the project here

### Documentation
Describe how we're documenting this project.  In some cases, the answer is "all in code/annotations and nothing else".  In others it's a full [MkDocs](https://www.mkdocs.org/) instance with user stories that are constantly updated throughout the life of the project.

### Acronyms
TMI - Too Much Information

### Things We Learned Together
Inside jokes and other fun memes bring teams together when working on projects, but can feel exclusionary to new team members.  List your jokes and personable notes here to help bring your new team members up to speed.

What else am I missing?

**Comment by sean-e-dietrich** [comment]
@thejimbirch I'm not sure the Inside Jokes should be added here but in Team work mainly if we ever turn over the repo to the client.

**Comment by thejimbirch** [comment]
Updated the Inside Joked section and added a Documentation section.  Thanks @drnikki @sean-e-dietrich
